Antiz96/arch-update

- install.sh
> Release 1.3.0

- README.md
- src/man/arch-update.1
- Added information to the man page/documentation
- Typo fixes
> Release 1.3.1

- src/script/arch-update.sh
I forgot to bump the script's version to v1.4.1 in the last release :disappointed:
> Bump the script's version to v1.4.2

- src/script/arch-update.sh
Bump the script to v1.5.0 for the related release.
> Bump the script to v1.5.0

- README.md
- src/script/arch-update.sh
This PR aims to add basic but useful information at the top of the main script (description, url & license) as well as updating the description in the README.
> Add basic but useful information at the top of the main script

- README.md
- doc/man/arch-update.1
- src/script/arch-update.sh
This PR aims to refactor the whole main script by making use of functions (instead of putting all the code directly in the `case` statement).
It improves significantly the script's readability and evolution easiness.
> Refactoring the script with functions

- src/script/arch-update.sh
This PR aims to bump the script to v1.5.4 in preparation of the future release.
> Bump the script to v1.5.4

- doc/man/arch-update.1
- src/script/arch-update.sh
Last round of fixes on the main script before the new release
> Various fixes

- .github/workflows/test.yml
This PR aims to add [codespell](https://github.com/codespell-project/codespell) to the test suite ran on pull request by the GitHub action.
> Add codespell to the test suite ran by GH action

- src/script/arch-update.sh
This PR aims to bump the main script version in preparation of the future release.
> Bump the main script version

- .github/workflows/test.yml
- src/script/arch-update.sh
This PR aims to improve and simplify the CI by using GH `actions/checkout` instead of cloning the repo inside the container.
> Improve/Simplify CI

- src/script/arch-update.sh
This PR aims to refactor the 'news printer' function to show more relevant information about the printed news in a more readable way:
```
---
Author: 'First_name Last_Name'
Publish date: 'Year-Month-Day'
URL: 'URL_of_the_news'
---
'Article content'
```
> Refactor the 'news printer' function to show more relevant info in a more readable way

- src/script/arch-update.sh
This PR aims to add the title of the printed article in the top information, in addition of the author, publication date and URL.
See #39
> Add the title of the printed article in the information

- src/script/arch-update.sh
This PR aims to bump the main script's version regarding the incoming new release.
> Bump the main script's version

- .github/workflows/mdl_style.rb
- .github/workflows/test.yml
- README.md
This PR aims to add [mardown lint](https://github.com/markdownlint/markdownlint) to the test CI.
> Add mdl to the test CI

- README.md
This PR aims to remove useless spaces in README
> Remove useless spaces

- src/script/arch-update.sh
> Bump the script version (1.6.0)

- src/script/arch-update.sh
> [Release Prep] Bump the script to v1.6.2

- src/script/arch-update.sh
> [Release Prep] Bump the script to v1.7.0

- res/completions/arch-update.zsh
> Fix a typo in ZSH completions

- src/script/arch-update.sh
instead of doing it manually :)
> Use the 'state_up_to_date' function to initialize the state file if it does not exists

- res/desktop/arch-update.desktop
Fixes https://github.com/Antiz96/Arch-Update/issues/178
> [FIX] Add a category to the desktop file

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/other.md
Add some fixes to issue templates
Partially addresses https://github.com/Antiz96/arch-update/issues/183
> chore: Update issue templates

- .github/ISSUE_TEMPLATE/config.yml
Add a config for issue templates to disable blank issues and add a link to the contributing guidelines
Partially addresses https://github.com/Antiz96/arch-update/issues/183
> chore: Add a config for issue templates

- .github/FUNDING.yml
Add FUNDING.yml with a link to the GitHub sponsor page
> chore: Add a link to sponsor page

- CONTRIBUTING.md
Add to create a merge request from a dedicated branch (and not using the main one) to CONTRIBUTING.md
> chore(CONTRIBUTING): Update contributing guidelines

- RELEASE.md
Unset the TAG variable once the release is created
> chore(release): Update RELEASE.md

- README-fr.md
- doc/man/fr/arch-update.1
- doc/man/fr/arch-update.conf.5
- po/fr.po
Typo fixes in FR README, man pages and po files
> style: Typo fixes in french resources

- src/script/arch-update.sh
Add a proper SPDX license header
> chore(main script): Add a proper SPDX license header

- src/script/arch-update-tray.py
Fixes missing tray icon title on Plasma.
Fix #201
> fix: fix tray icon title on Plasma

- po/arch-update.pot
- po/fr.po
- src/script/arch-update.sh
Better to state what actually went wrong rather than trying to guess the cause
> chore(news): Simplify warning message in case of request timeout

- CONTRIBUTING.md
Just some little wording correction/improvements to CONTRIBUTING.md
> style(CONTRIBUTING): Improve wording in contributing guidelines

- src/lib/check.sh
Fix missing icon on "updates available" desktop notifications.
> fix: Fix missing icon on notifications

- README-fr.md
- README.md
- doc/man/fr/arch-update.1
- po/fr.po
Update screenshots in the READMEs with the new systray's dropdown menu added in https://github.com/Antiz96/arch-update/pull/272
Also includes a slight improvement to the french translation.
> doc: Update screenshots in the READMEs with the new systray's dropdown menu

- .github/ISSUE_TEMPLATE/other.md
Add the 'question/feedback' label to issues with the 'Other' type
> chore(issues): Add a dedicated label to the 'Other' issue type

- CONTRIBUTING.md
Shout out to Arch-Update's Stargazers and everyone who contributed one way or another! <3
> chore(CONTRIBUTING.md): Expand the "Thank you" section

- src/lib/check.sh
- src/lib/common.sh
Only check for 'notify-send' presence if the NoNotification option is not set
> chore: Improve logic for the 'NoNotification' option

- Makefile
- po/zh_CN.po
- src/lib/tray.py
> i18n: add zh_CN

- Makefile
- po/hu.po
- src/lib/tray.py
Add Hungarian (hu) translation
>  chore(i18n): add Hungarian translation

- po/arch-update.pot
- po/fr.po
- po/hu.po
- po/sv.po
- po/zh_CN.po
- src/lib/common.sh
- src/lib/tray.py
Use a more precise description of the logic applied to set the translation files (to avoid eventual confusions about the way it works) and remove unecessary related parts from the tray python scripts (which were added due to confusions about the way it works :P).
Also update the translation files lines number.
> chore(i18n): Update the logic to set the path to translation files

- po/hu.po
'updates' is the name reference of the file and therefore should not be translated
> style(i18n): Fix a word in Hungarian translation

- po/fr.po
Update French translation to include the new `-s / --services` option's description (added in https://github.com/Antiz96/arch-update/pull/369).
> chore(i18n): Update French translation

- po/de.po
Update German translation to include the new -s / --services option's description (added in #369).
> Update German translation to include the new -s / --services option's description (added in #369).

- README-fr.md
See https://github.com/Antiz96/arch-update/pull/378
> doc(README-fr): remove unnecessary sudo mentions

- README-fr.md
- README.md
Explicitly list all dependencies in documentation to match what's in the `PKGBUILD`.
> doc(deps): Update dependencies list

- README-fr.md
- README.md
- po/arch-update.pot
- po/de.po
- po/fr.po
- po/hu.po
- po/sv.po
- po/zh_CN.po
- src/lib/tray.py
Add action to the update entries to open the package website.
Closes https://github.com/Antiz96/arch-update/issues/403
> feat: Show package website when clicking on update entry

- po/arch-update.pot
- po/de.po
- po/fr.po
- po/hu.po
- po/sv.po
- po/zh_CN.po
- src/lib/common.sh
- src/lib/full_upgrade.sh
- src/lib/notification.sh
- src/lib/tray.sh
Use flock rather than an 'homemade' lockfile mechanism to make the logic more robust and avoid being hit by eventual race conditions.
> fix: Make lockfiles logic more robust
