README.md, doc/man/arch-update.1, src/script/arch-update.sh
This PR aims to add support for [doas](https://wiki.archlinux.org/title/Doas) which is a *lighter* alternative to sudo.
It also includes various improvements and optimizations to the main script and documentations (README/man page) and it bumps the `version` variable of the main script to `1.4.0` in anticipation of the new release that will be available soon.
=> Add support for doas

README.md, doc/man/arch-update.1, src/script/arch-update.sh
This PR aims to add support for [pacdiff](https://archlinux.org/packages/community/x86_64/pacman-contrib/) in order to be able to process potential pacnew/pacsave files after an update.
With this PR, `arch-update` now searches for pacnew/pacsave files after each update and offers to process them with `pacdiff` if there are.
This PR also includes a few improvements to the documentation (README/man page).
=> Add support for pacdiff to be able to process pacnew/pacsave files after an update

README.md, doc/man/arch-update.1, src/script/arch-update.sh
This PR aims to add a new feature into `arch-update` that offers the possibility to read the latest Arch Linux news before updating the system. 
It prints the title of the latest Arch Linux news and offers to expand their content.
Users can choose which news to read or can proceed to update without reading any if they want to.
This PR also includes a complete rework of the "screenshot" section of the README.
=> Add a feature to read the latest Arch Linux news before updating the system

README.md, doc/man/arch-update.1, src/script/arch-update.sh
This PR aims to add support for removing orphan packages.
After an update `arch-update` search for [orphan packages](https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Removing_unused_packages_(orphans)) and offers to remove them.
=> Add removing orphan packages support

README.md, doc/man/arch-update.1, src/script/arch-update.sh
This PR aims to make searching and processing orphan packages and pacnew files independent from updates.
`arch-update` will search for orphan packages and pacnew/pacsave files (and offer to process them if there are) even if there's no update available.
=> Make searching and processing orphan packages and pacnew files independent from updates

README.md, src/script/arch-update.sh
This PR aims to make the pacnew processing feature lists pacnew files before offering to process them.
`arch-update` gives the list of pacnew/pacsave files (in the same format as the list of packages available to update or orphan packages to remove) before offering to process them.
=> Make the pacnew processing feature lists pacnew files before offering to process them

README.md, doc/man/arch-update.1, src/script/arch-update.sh
This PR aims to add various improvements/optimisation to the main script, the README and the documentation (man page).
**Main script:**
- General improvements of the comments and "echoed" sentences (grammar corrections, more accurate details, better phrasing, gender neutral sentences, etc...)
- *Minor* code optimisations/better styling 
- Added error handling when an error occurs during the removal process of the orphan package(s)
**README:**
- General improvements (grammar corrections, more accurate details, better phrasing, etc...)
**Documentation:**
- General improvements (grammar corrections, more accurate details, better phrasing, etc...)
=> Various improvements/optimisation to the main script, the README and the documentation

src/script/arch-update.sh
This PR aims to make use of `pacdiff` to search for pacnew files instead of using `find` (since `pacdiff` has such feature and is already used to process pacnew files).
=> Make use of pacdiff to search for pacnew files

src/script/arch-update.sh
`yay` recently introduced a new behavior in its "checkupdate" function (in this [PR](https://github.com/Jguer/yay/pull/1915)) which now prints the following sentence:
```
user@Arch-Linux ~ yay -Qua
:: Searching AUR for updates...
```
This produces "false positive" with `arch-update` which thinks there are updates available (even if there are not) because of this output.
This pull request aims to fix this issue.
=> Fix the 'checkupdate' issue when using yay

src/script/arch-update.sh
Revert the fix pulled in #22 as it has been fixed/reverted directly in `yay` by upstream (see https://github.com/Jguer/yay/issues/2057 and https://github.com/Jguer/yay/pull/2060).
=> Revert the needed fix for the 'checkupdate' issue when using yay (#22) as it has been fixed/reverted in upstream

README.md, doc/man/arch-update.1, src/script/arch-update.sh
This PR aims to add a clear and concise help message instead of simply printing the man page for the --help option.
=> Add a clear and concise help message (instead of simply printing the man page) for the --help option

README.md, doc/man/arch-update.1, src/script/arch-update.sh
This PR aims to make use of separated exit codes for each type of errors in order to simplify potential debugging.
=> Use separated exit codes for each type of errors

README.md, src/script/arch-update.sh
This PR aims to switch from [hq](https://github.com/coderobe/hq) to [htmlq](https://github.com/mgdm/htmlq) for printing Arch news during the `update` operation as `htmlq` is slightly faster and prints a slightly better formatted output than `hq` in that particular case.
Huge love to `hq` which an amazing project, go star it! <3
=> Switch from hq to htmlq to print Arch news during the update operation

src/script/arch-update.sh
This PR aims to add more `sed` filters on special characters/symbols when parsing the Arch news urls to avoid processing a wrong url during the `list_news` function, resulting in an empty printed news.
=> Filter all special characters/symbols when parsing the Arch news urls to avoid ending with a wrong url

doc/man/arch-update.1, src/script/arch-update.sh
This PR aims to make some typo fixes
=> Typo fixes

src/script/arch-update.sh
This PR aims to add a '[NEW]' tag to each Arch news that are newer than 15 days when printing the news title so the user can quickly identify a recently published news:
```
1 - Title 1 [NEW]
2 - Title 2 [NEW]
3 - Title 3
4 - Title 4
5 - Title 5
```
=> Add a '[NEW]' tag to each Arch news that are newer than 15 days

README.md, doc/man/arch-update.1
This PR aims to update the documentation with the features added in #39 #40 #41
=> Update documentation with the recently added features

README.md, doc/man/arch-update.1, src/script/arch-update.sh
This PR aims to bring *optional* Flatpak support to `arch-update`:
- Include Flatpak packages in the count/listing of available updates and update them during the `update` function.  
- Also offer to remove unused Flatpak packages after an update.
- Documentation updated accordingly.
Obviously requires the [`flatpak` cli](https://archlinux.org/packages/extra/x86_64/flatpak/).
Fixes #52
=> Add Flatpak support

src/script/arch-update.sh
This PR aims to add some basic styling to differentiate each steps (and substeps) of the main script more easily. 
This makes the script more "transparent" about what it does and will also be useful for eventual debugging.
=> Add styling to differentiate each steps of the main script more easily

src/script/arch-update.sh
This PR aims to add a condition to only print "No Flatpak unused package found" if flatpak is actually installed to prevent people not having the `flatpak` cli installed seing this irrelevant message.
=> Only print "No Flatpak unused package found" if flatpak is actually installed

README.md, doc/man/arch-update.1, src/script/arch-update.sh
Before that commit, the default behaviour was to not show the version changes when listing the available repo/AUR packages updates. Showing them was an option.
This commit aims to revert that behaviour (showing the version changes by default and make hiding them an option). Indeed, version changes is an important and useful information which makes more sense being shown by default.
The documentation has been adapted accordingly regarding the required command to hide version changes for people that prefer not showing them.
=> Make showing the version changes the default behaviour when listing available updates

README.md
`vim` is the default merge program for `pacdiff` but [other programs can be used instead](https://wiki.archlinux.org/title/Pacman/Pacnew_and_Pacsave#pacdiff).
Also, a merge program isn't necessarily required to simply "`R`emove pacnew" or "`O`verwrite with pacnew".
Regarding that, making `vim` an optional dependency makes sense and avoid forcing its installation to people that prefer to use another program instead.
=> Make vim an optional dependency

src/script/arch-update.sh
Currently, the desktop notification included in the `check()` function is sent whenever there are update available without any sort of filter. 
That means that, with the systemd timer triggering the `check()` function each hour,  you will get a notification for the same exact available updates each hour over and over until you actually apply them (in the eventuality that there's no other available updates in the mean time).
This commit makes the `check()` function verify that the current list of available updates differs from the one obtained by the last check before re-sending a notification. 
That way, a new notification is sent only if there are new available updates compared to the last check so you don't get multiple notifications for the exact same update over time.
=> Only send desktop notification if the list of available updates differs from the last check

README.md, doc/man/arch-update.1, src/script/arch-update.sh
This MR aims to restructure the functions calls so they are now completely independent from each other, in the sense that no function is making a direct call to another one anymore (except for the 'changing icon' ones).
This makes the script more readable and easier to evolve/work with, as now the functions calls are centralized in the last 'case' statement instead of having both the 'list_packages' and the 'update' function calling other functions depending on certains parameters (which made adding a new function unnecessarily complex).
=> Restructuration of the functions' calls in the script to make it more readable and easier to evolve/work with

doc/man/arch-update.1, src/script/arch-update.sh
EndeavourOS does not use `/boot` to store `vmlinuz*` files when using systemd-boot (I couldn't find much details about a specific reason for that, attempts at analyses [here](https://github.com/Antiz96/arch-update/issues/74#issuecomment-1839544849).
This PR aims to make the script fallback to `/usr/lib/modules/*/vmlinuz*` if `vmlinuz*` files are not found under `/boot`. This prevents false positive and intempestive 'pending kernel update' messages on EndeavourOS + systemd-boot.
Fixes https://github.com/Antiz96/arch-update/issues/74
=> Fix false positive and intempestive 'pending kernel update' messages on EndeavourOS with systemd-boot

doc/man/arch-update.1
Changes the script version in the man page (`v1` => `1.9.1`) to be consistent with the version in `src/script/arch-update.sh`.
=> Update version number in Arch-Update manual

README.md, doc/man/arch-update.1
Fixes https://github.com/Antiz96/arch-update/issues/82
=> Update documentation to advice using 'systemctl edit' to modify the auto-check cycle

README.md, src/script/arch-update.sh
This PR aims to add colors to the output of the script for a better readibility and a nicer 'look'.
Colors are inspired by what's used in [libmakepkg](https://gitlab.archlinux.org/pacman/pacman/-/blob/v6.0.2/scripts/libmakepkg/util/message.sh.in).
This PR also brings some small code refactoring for a better readibility of the script.
Closes https://github.com/Antiz96/arch-update/issues/81
=> Add colors to the output of the script

README.md, src/script/arch-update.sh
Fixes https://github.com/Antiz96/arch-update/issues/86
=> Add missing documentation for the old cached packages handling and pending kernel update processing features in the help message

Makefile, README.md, doc/man/arch-update.1, doc/man/arch-update.conf.5, src/script/arch-update.sh
This PR aims to add an *optional* configuration file for `arch-update` to enable/disable or modify certain options within the script.
The configuration file has to be located in `${XDG_CONFIG_HOME}/arch-update/arch-update.conf` or `${HOME}/.config/arch-update/arch-update.conf`.
As of now, the supported options are:
- NoColor # Do not colorize output.
- NoVersion # Do not show versions changes for packages when listing pending updates.
- NoNews # Do not print Arch news. Note that using this option will generate a warning message as reminder that users are expected to regularly check Arch news.
- KeepOldPackages=Num # Number of old packages' versions to keep in pacman's cache. Default is 3.
- KeepUninstalledPackages=Num # Number of uninstalled packages' versions to keep in pacman's cache. …
=> Add an optional configuration file to enable/disable or modify certain options

README.md, doc/man/arch-update.1
`OnUnitActiveSec` parameter first has to be reset before adding a custom configuration, otherwise the custom parameter will be **added** to the already existing one instead of acting as a replacement.
Fixes https://github.com/Antiz96/arch-update/issues/96
=> Correction of documentation regarding how to change the auto-check cycle

.github/workflows/CI.yml, Makefile, README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1, doc/man/fr/arch-update.conf.5
This PR aims to bring a french translation for the `Arch-Update` documentation (namely the README and the man pages).
Both READMEs (english and french) have a link back and forth between each other.
Once a new release is tagged, the french version of the man pages will be the default one for system set up with french language.
The french translation of the script itself will follow.
=> French translation for the documentation (README + Man pages)

src/script/arch-update.sh
This commit aims to make the Flatpak updates detection more robust by filtering the 'flatpak update' command output to remove everything placed before the listing of available updates.
This avoid potential false positives in Arch-Update's listing as it ensure that everything placed above the listing of available updates in the 'flatpak update' output will not be included in the list (such as info, warning, etc...).
The complete output is still shown when the Flatpak updates are actually applied during the script, so users are still aware of potential info/warnings.
Fixes https://github.com/Antiz96/arch-update/issues/103
=> Make Flatpak packages updates detection more robust to avoid false positives

src/script/arch-update.sh
Arch-Update is licensed under the GPL-3.0 license or any later version of that same license. 
SPDX identifier: GPL-3.0-or-later
=> Licensing: Precise that Arch-Update is licensed under GPL3+

.github/workflows/CI.yml, Makefile, README-fr.md, po/arch-update.pot, po/fr.po, src/script/arch-update.sh
This PR aims to bring a french translation for the `Arch-Update` script.
A template `arch-update.pot` file is available in the `po` folder for eventual future translations.
This PR also brings several improvements to the `Makefile` and the overall packaging method.
Closes #93
=> French translation for the main script

README.md, doc/man/arch-update.1, doc/man/arch-update.conf.5, doc/man/fr/arch-update.1, po/arch-update.pot, po/fr.po, src/script/arch-update.sh
Basically replace 'print' by 'display' everywhere. It sounds more accurate.
=> Improve documentation wording

README-fr.md, README.md, doc/man/arch-update.1, doc/man/arch-update.conf.5, doc/man/fr/arch-update.1, doc/man/fr/arch-update.conf.5, po/arch-update.pot, po/fr.po, src/script/arch-update.sh
This PR aims to bring options allowing to customise the number of Arch news to display before updating and with the `-n/--news` option.
Users can now optionally specify the number of Arch news to display for the current execution when using the `-n/--news` option, like so: `arch-update --news 10`.
Users can permanently set the number of Arch news to display before updating and with the `-n/--news` option by setting the `NewsNum=[Num]` option in `arch-update.conf`, like so: `NewsNum=10`
The default value is 5.
Closes #111
=> Allow to customise the number of Arch news to display before updating and with the `-n/--news` option

README-fr.md, README.md, doc/man/arch-update.1, doc/man/arch-update.conf.5, doc/man/fr/arch-update.1, doc/man/fr/arch-update.conf.5, po/arch-update.pot, po/fr.po, src/script/arch-update.sh
This PR aims to makes Arch news displaying more relevant by only displaying them if at least a new one had been published since the last `arch-update` run (instead of being displayed systematically, which is irrelevant/useless most of the time).
Arch news published since the last run are tagged as `[NEW]`.
One can still use the 'old' behavior (always display Arch news before updating, regardless of whether there's a new one since the last run or not), by setting the `AlwaysShowNews` option in `arch-update.conf`.
With this new behavior, the `NoNews` option (suggested in #85 and introduced in #89) is deprecated and completely removed since it's not relevant anymore.
Closes #110
=> Only display Arch news if a new one has been published since the last run

doc/man/arch-update.1, doc/man/fr/arch-update.1
Remove useless '.RB' and 'see also' statements in man pages
=> General cleanup of man pages

Makefile, res/completions/arch-update.bash, res/completions/arch-update.fish, res/completions/arch-update.zsh
This PR aims to introduce basic shell completions for `bash`, `zsh` and `fish` for the `arch-update` command.
=> Add shell completions for bash, zsh and fish

README-fr.md, README.md, doc/man/arch-update.1, doc/man/arch-update.conf.5, doc/man/fr/arch-update.1, doc/man/fr/arch-update.conf.5, po/arch-update.pot, po/fr.po, src/script/arch-update.sh
Introduce the new `arch-update -l`/`arch-update --list` option that simply displays the list of pending updates (including AUR packages if yay/paru is installed and flatpak packages if flatpak is installed).
This option allow users to get the list of pending updates in a non-interactive way, e.g. to have it scheduled in a cronjob to get the list of pending updates automatically and periodically. It basically acts like `checkupdates`, except it includes AUR and flatpak packages (if the related dependencies are installed).
Closes #122
=> Add the new `-l/--list` option to simply get the list of pending updates

res/completions/arch-update.bash, res/completions/arch-update.fish, res/completions/arch-update.zsh
=> Add -l/--list option to bash/fish/zsh completion

src/script/arch-update.sh
The fix implemented for EndeavourOS in https://github.com/Antiz96/arch-update/pull/75 can create false positives in case some old-ish/outdated kernel related files are [laying in /boot](https://github.com/Antiz96/arch-update/issues/74#issuecomment-2013160918) *for some reasons... (?)* 
This commit aims to make the pending kernel update detection more robust to avoid such potential false positives by making Arch-Update looking for kernel related files in **both** /boot and in /usr/lib/modules/* (instead of falling-back to the latter only if kernel files are not found in the former).
Fixes https://github.com/Antiz96/arch-update/issues/74
=> git commit -m "Make the pending kernel update detection more robust (for EndeavourOS)

po/arch-update.pot, po/fr.po, src/script/arch-update.sh
This PR aims to improve the current notification behavior by replacing the previously sent desktop notification (instead of sending a new one) during the check function, to avoid having notifications stacking over time if they are not cleared.
With this new behavior, Arch-Update will new notifications by replacing the ID of the previous one, acting as an "update" of the previously sent notification instead of simply sending a new one. Thanks to this, Arch-Update will only show one (and only one) notification in the notification history/center (being updated on the fly if needed). 
Of course, when a notification is being updated, it is still pushed to the user as if a new one has been sent.
Closes https://github.com/Antiz96/arch-update/issues/133
=> Replace the previously sent desktop notification instead of sending a new one during the check function

MAINTAINERS.md
Add a trust path for users
This file contains the maintainers that are trusted and are allowed to cut and sign git tags and release artifacts for this project.
As a user, you can *(and should)* verify that git tags and auto-generated source tarballs on releases (tar.gz archives) for this project are signed by one of the person listed in this file (with the associated GPG key).
If a git tag and/or an auto-generated source tarball (tar.gz archive) contained in a release of this project cannot be verified (e.g. it is not signed / it is signed with a GPG key or by a person that is not listed in this file), the associated tag/release/artifact(s) should not be trusted (starting from now).
=> Add a trust path for users

po/arch-update.pot, po/fr.po, src/script/arch-update.sh
Paru recently changed the way [the color output are automatically enabled](https://github.com/Morganamilo/paru/commit/b345771e91261b2eb19d33d8e3c192bd0be14051), resulting in a non-colored output when executing `arch-update`.
This PR aims to fix that by enforcing the color option depending on the presence of the `NoColor` option in `arch-update.conf` (`--color always|never`) for Paru but also for every wrapped tool in the main script (pacman, yay/paru, pacman-contrib tools, etc...) to avoid such issue in the future.
=> Explictely set color option of wrapped tool in the main script

po/arch-update.pot, po/fr.po, src/script/arch-update.sh
On a poor network connection and/or with a long list of pending updates, the script might take some time to look for and generate the list of packages available to update.
Without an explicit/clear indicator that the script is actually looking for updates, one could think that it is 'stuck'. This commit introduces an explicit message that the script is currently looking for updates to avoid people thinking it hanged up.
=> Add an explicit message that the script is looking for updates

Makefile, README-fr.md, README.md, res/desktop/arch-update.desktop, src/script/arch-update.sh
=> Move icons into hicolor theme

README-fr.md, doc/man/fr/arch-update.1
=> Fix a typo in the FR documentation

README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1, src/script/arch-update-tray.py
This PR makes the systray applet searching for the .desktop file in the following path (in that specific order):
- $XDG_DATA_HOME/applications/arch-update.desktop
- $HOME/.local/share/applications/arch-update.desktop
- $XDG_DATA_DIRS/applications/arch-update.desktop
- /usr/local/share/applications/arch-update.desktop
- /usr/share/applications/arch-update.desktop
That would allow users to be able to provide a customized `.desktop` file for the systray applet to execute if needed (e.g. force Arch-Update to launch in a specific terminal emulator that is [not supported](https://github.com/Antiz96/arch-update/blob/main/src/script/arch-update-tray.py#L15) by gio/glib2).
Fixes https://github.com/Antiz96/arch-update/issues/151
=> Make systray applet also searching in XDG_DATA_HOME & XDG_DATA_DIRS when looking for the .desktop file

README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1, po/arch-update.pot, po/fr.po, src/script/arch-update.sh
- Add a precision in the documentation that the check function only sends a desktop notification if the list of pending updates differs from the last check (in other words, that there is at least one **new** update available compared to the last check).
- Advise using `systemctl --user edit --full` instead of a "regular" edit to modify the check cycle. While it is "overkill" in most cases, it is less complex/confusing to use and allow more flexibility (for instance, it allows to get completely rid of a parameters and not just to modify its value). The `arch-update.timer` is not subject to change upstream wise so there's no apparent issue recommanding using a `--full` edit.
Fixes https://github.com/Antiz96/arch-update/issues/164
=> Improve documentation regarding the check function and how to modify the check cycle

po/arch-update.pot, po/fr.po, src/script/arch-update.sh
This commit makes the 5 seconds countdown before a reboot to apply a pending kernel update show the remaining seconds in real time.
=> Make the reboot countdown after a kernel upgrade showing remaining seconds in real time

po/arch-update.pot, po/fr.po, src/script/arch-update.sh
This commit aims to make Arch-Update also look in XDG_DATA_HOME/XDG_DATA_DIRS for translation files and example config (instead of assuming the `/usr` or the `/usr/local` prefix during install).
Fixes https://github.com/Antiz96/arch-update/issues/166
=> Make Arch-Update also look in XDG_DATA_HOME/XDG_DATA_DIRS for translation files and example config

README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1, po/arch-update.pot, po/fr.po, src/script/arch-update.sh
Add `run0` support as a fallback option if neither `sudo` nor `doas` are found.
Closes https://github.com/Antiz96/arch-update/issues/171
=> Add support for systemd run0

po/arch-update.pot, po/fr.po, src/script/arch-update-tray.py
This is to address pylint [E0606](https://pylint.pycqa.org/en/latest/user_guide/messages/error/possibly-used-before-assignment.html) warning in CI.
=> Assign the STATE_FILE var before it is accessed in arch-update-tray.py script

README-fr.md, README.md, doc/man/arch-update.1, doc/man/arch-update.conf.5, doc/man/fr/arch-update.1, doc/man/fr/arch-update.conf.5, po/arch-update.pot, po/fr.po, res/config/arch-update.conf.example, src/script/arch-update.sh
This PR introduces the 'PrivilegeElevationCommand' option to the arch-update.conf configuration file which allows to explicitly set the command to be used to elevate privileges (sudo, doas, run0), so people can choose between them if they have multipe of those commands installed.
If this option isn't set, the default behavior is applied (first look for `sudo`, then `doas`, then `run0`).
Closes https://github.com/Antiz96/arch-update/issues/173
=> Add an option in the configuration file to explicitely set which elevation command to use

README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1, po/arch-update.pot, po/fr.po, res/completions/arch-update.bash, res/completions/arch-update.fish, res/completions/arch-update.zsh, src/script/arch-update.sh
This PR introduces the `--show-config` option that displays the current configuration file (arch-update.conf), if it exists.  
This will be useful for debug/analyses during bug report if needed.
Closes https://github.com/Antiz96/arch-update/issues/176
=> Add the `--show-config` option that displays the current configuration file

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other.md, .github/PULL_REQUEST_TEMPLATE.md
Add templates for issues and pull requests to categorize each possible issue type properly and ask some relevant details to users in order to ease processing
Partially addresses https://github.com/Antiz96/arch-update/issues/183
=> chore: Add templates for issues and pull requests

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README-fr.md, README.md
Add contributing guidelines (CONTRIBUTING.md) to the repo in order to define rules, standard and general guidelines for every future contributions and interactions in this project.
Addresses parts of https://github.com/Antiz96/arch-update/issues/183
=> chore: Add contribution guidelines (CONTRIBUTING.md)

CHANGELOG.md, RELEASE.md, cliff.toml
Add a RELEASE.md file containing every steps required to create a new release
Closes https://github.com/Antiz96/arch-update/issues/183
=> chore(release): Add release steps

po/arch-update.pot, po/fr.po, src/script/arch-update.sh
The "WARNING" and "ERROR" words (used when printing a warning or an error messages to users) were missing from the translations files and were thus printed as such whatever language is used.
Before the fix:
After the fix:
Fixes https://github.com/Antiz96/arch-update/issues/182
=> fix(translation): Add missing translations for WARNING and ERROR

Makefile, README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1, po/arch-update.pot, po/fr.po, res/desktop/arch-update-tray.desktop, src/script/arch-update.sh
Add the optional `--enable` argument to the `--tray` option to automatically set the systray applet in the autostart apps by copying the "arch-update-tray.desktop" file to `${XDG_CONFIG_HOME:-${HOME}/.config}/autostart/arch-update-tray.desktop`.
Closes https://github.com/Antiz96/arch-update/issues/180
=> feat: Add the `--tray --enable` option to automatically set the systray applet in autostart apps

po/arch-update.pot, po/fr.po, src/script/arch-update.sh
Add a test to check if there's already a running instance of the systray applet before starting it to avoid the possibility to have multiple instances running at the same time.
Fixes https://github.com/Antiz96/arch-update/issues/196
=> fix(systray): Prevent multiple instances of the systray applet to be able to run at the same time

README-fr.md, README.md, po/arch-update.pot, po/fr.po, src/script/arch-update.sh
Add the possibility to read multiple news at once by selecting multiple number entries (e.g. 1 3 5). Selecting 0 reads them all.
Closes https://github.com/Antiz96/arch-update/issues/198
=> feat: Allow to read multiple news at once

README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1, po/arch-update.pot, po/fr.po, src/script/arch-update.sh
Check if any services need to be restarted after updating and offers to do so (if there are). The listing of the services is done via `checkservices` from [archlinux/contrib](https://github.com/archlinux/contrib) (available in the [extra] [archlinux-contrib](https://archlinux.org/packages/extra/any/archlinux-contrib/) package). 
**Important notes:**
- The services that may need a post upgrade restart are only checked if an actual package(s) upgrade has been performed by `arch-update` beforehand. This is because the listing of services via `checkservices` requires elevated privileges (as it needs to run `systemctl daemon reload/reexec`), and it would be unexpected to ask for a `sudo/doas/run0` password **everytime** arch-update is executed (even if there's no update available). Checking …
=> feat: Check for services that require a post upgrade restart on packages upgrade

README-fr.md, README.md, doc/man/arch-update.conf.5, doc/man/fr/arch-update.conf.5, po/arch-update.pot, po/fr.po, res/config/arch-update.conf.example, src/script/arch-update.sh
Add the `DiffProg` option in the `arch-update.conf` configuration file to explicitly set which diff program to use during the processing of pacnew files with pacdiff.
Closes https://github.com/Antiz96/arch-update/issues/204
=> feat: Add the "DiffProg" option in arch-update.conf

doc/man/arch-update.1, doc/man/fr/arch-update.1
Add the missing documentation for the exist status 12 in man pages
=> doc: Add the exit status 12 documentation in man pages

src/script/arch-update.sh
The exit status code 7 invoked if there are no pending update when using the `-l/--list` option was not honored because of the `sed` part piped into the call of the `list_package` function. Indeed, piped commands are executed in their own subshell, so the subshell invoked by the `| sed` part is exited with status code 7 instead of the parent subshell (see https://www.gnu.org/software/bash/manual/html_node/Pipelines.html & https://relentlesscoding.com/posts/bash-commands-in-pipelines-subshells/ for more details). Given the very little benefit this `sed` part brings (namely removing the last blank line of the output for purely aesthetic reason), it's not worth wrapping our head too hard on this. Let's just drop it.
This commit also adds an info message that there is no update available for …
=> fix: Fix exit status code 7 for the --list option

po/arch-update.pot, po/fr.po, src/script/arch-update.sh
This commit brings multiple improvements to the "News" function of the main script in order to optimize it and avoid unexpected behaviors:
- Print a message when Arch-Update is looking for recent Arch News (to avoid people thinking the script is just stuck in case it takes some time due to network instability/slowness)
- Print a message if no recent Arch News has been found since the last run
- Optimize the curl requests by merging the two first ones into a single one
- Add a default 30 sec timeout (`--max-time 30`) to curl requests so they don't end taking multiple minutes on slow/faulty network connection). If the timeout is reached, Arch-Update prints a warning explaining that it wasn't able to retrieve Arch News in a reasonable time, prints the URL of the Arch website or the URL of …
=> fix: Optimize the "News" function and avoid unexpected behaviors

po/arch-update.pot, po/fr.po, src/script/arch-update-tray.py
Add SPDX license identifier header to the arch-update-tray python script
=> chore: Add SPDX license identifier header to the tray script

src/script/arch-update.sh
This commit avoids undesired ` [: : integer expression expected` error message in case the `last_update_run` file is incorrect (e.g. it does not contain a properly formatted date) during the news check.
=> fix: Avoid undesired error message if the last_update_run file is incorrect during news check

src/script/arch-update.sh
This commit updates the checkservices command used to parse the list of services to restart after upgrades in order to adopt a more elegant way to retrieve the said list, matching the recent upstream changes made to checkservices. 
See https://github.com/archlinux/contrib/compare/20240714...20240720
=> chore(checkservices): Update the checkservices command that parses the list of services to restart

po/arch-update.pot, po/fr.po, src/script/arch-update.sh
This commit makes curl fail on http server errors response (e.g. archlinux.org is down or under huge loads, responding http error code 504, 502, etc...).  
This is to prevent getting wrongly formatted news list in such scenarios, resulting in an unexpected error and incorrectly formatted news display.
```
==> Arch News:
/usr/bin/arch-update: line 388: [: : integer expression expected
1 - 
```
=> fix(news): Make curl fail on http server errors responses when checking for recent news

src/script/arch-update.sh
Since https://github.com/Antiz96/arch-update/commit/384b6bcac90cb82bf7082f9ae1e2691fbf0b4e43, not only timeout are checked but also HTTP error responses. This commit updates the value of the news var to a more generic name in case of error.
=> chore: update the news var value in case of error

README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1, po/arch-update.pot, po/fr.po, src/script/arch-update.sh
Currently, when an update requires both to reboot and restart the services, it proposes first to restart the services and then to reboot.
If the reboot is proposed and accepted, then restarting the services is a useless operation.
I propose thus to propose the reboot before restarting the services.
Closes https://github.com/Antiz96/arch-update/issues/224
=> Ask to reboot before restarting the services

README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1
As a precision and justification of the project's overall design, add that Arch-Update follows usual system maintenance steps, as described in the Arch Wiki at https://wiki.archlinux.org/title/System_maintenance.
=> doc: Add that Arch-Update follows usual system maintenance steps (as described in the Arch Wiki) in documentation

src/script/arch-update.sh
Archweb recently switched date format from `01-01-2024` to `Jan. 01, 2024`, breaking the date parsing during the Arch news listing/displaying. This commit updates the date parsing accordingly to fix the "invalid date" error during the news listing and the incorrect "Author/Date" fields when displaying a news.
Before: 
After:
=> fix: Fix dates parsing on news listing/displaying

README-fr.md, README.md, doc/man/arch-update.conf.5, doc/man/fr/arch-update.conf.5, po/arch-update.pot, po/fr.po, res/config/arch-update.conf.example, src/lib/common.sh, src/lib/config.sh
Add the `AURHelper` option in the `arch-update.conf` configuration file to explicitly set which AUR helper to use for the optional AUR packages support.
Closes https://github.com/Antiz96/arch-update/issues/231
=> feat: Add the "AURHelper" option in arch-update.conf

Makefile, README-fr.md, README.md, src/arch-update.sh, test/case/basic_functions.bats
Tests are executed with `bats`.
Currently it checks the "version" and "help" function (this notably verifies that libraries are correctly sourced and called from the main script).
Closes https://github.com/Antiz96/arch-update/issues/234
=> chore: Add simple unit tests to check basic functions with `make test`

README-fr.md, README.md
fakeroot is now an optional dependency for pacman-contrib (and not a 'hard' dependency anymore). It is required for `checkupdates` and should now be declared as an explicit dependency for Arch-Update
https://gitlab.archlinux.org/archlinux/packaging/packages/pacman-contrib/-/merge_requests/1
Fixes https://github.com/Antiz96/arch-update/issues/235
=> fix: Add fakeroot as an explicit dependency

po/arch-update.pot, po/fr.po
The french translation hasn't been updated to reflect changes made in https://github.com/Antiz96/arch-update/commit/6a4bfe05914f7faab4d93475b99d2c81e41322c7, causing it to be missing.
Before:
After:
Fixes https://github.com/Antiz96/arch-update/issues/238
=> fix: Add the missing french translation on the "AUR helper not found" warning

src/lib/check.sh, src/lib/common.sh, src/lib/list_packages.sh, src/lib/tray.py, src/lib/tray.sh, src/lib/update.sh
The "current_state" file and the related functions are in fact only used to determine which icon the systray applet should display (depending on the current state of the system). Recording the current state of the system (up to date/updates available) is not necessary for any other stages (not currently at least), so it makes sense adopting a more suited & precise name.
=> chore: Rename "state" functions & file to "(tray) icon"

Makefile
Some new icons color set for the systray applet will be added soon and we are planning to make additional users contributed colors as easy as possible to implement (see https://github.com/Antiz96/arch-update/issues/240). 
Adopting a more "dynamic" way to install icons in the Makefile will avoid having to modify it each time a new icons color set is added.
=> chore: Make icon installations more dynamic in the Makefile

Makefile, src/lib/gen-config.sh
Move the arch-update.conf.example configuration file to the DATA system (as defined by XDG base directory): `${PREFIX}/share/arch-update/config/`. According to standards, it makes more sense to have it there than in `${PREFIX}/share/doc/arch-update/`.
=> chore: Move example config to the XDG DATA directory

.github/workflows/CI.yml
Add a `make test` stage to the CI GitHub action so `make test` is executed on pull request (to ensure the changes made are not breaking units tests).
=> chore: Add `make test` to the CI

src/arch-update.sh, src/lib/common.sh, src/lib/config.sh
Streamline option checking in the `arch-update.conf` configuration file by optimizing the way each option are checked and the way the related variables are set:
- `lib/config.sh` is now dedicated to checking options set in `arch-update.conf`
- Options are only checked if the `arch-update.conf` file is found/exists
- Values for the variables related to each options are now directly set with the output of `grep` (instead of running grep twice; once to check the validity of the set value and once to affiliate the value with the variable).
=> chore: Streamline option checking in arch-update.conf

README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1
Highlight the `arch-update --tray --enable` as the preferred method to automatically start the systray applet at boot. Indeed, XDG Autostart should work with most desktop environments (while the systemd service fails on a bunch of them, e.g. XFCE, LXQT, etc...).
=> doc: Improve documentation about starting the systray applet at boot

README-fr.md, doc/man/arch-update.1, doc/man/fr/arch-update.1
Oversight of this commit: https://github.com/Antiz96/arch-update/commit/1349ad5a70962f5106980abf730d4c618fa825ff
=> doc: Update man pages about how to start the systray applet at boot

po/arch-update.pot, po/fr.po, src/lib/tray.py
Add a right click menu entry to check for updates in the systray applet (runs `arch-update --check`), allowing to easily trigger a check for new pending updates without having to actually run `arch-update` by cliking systray or waiting for the systemd timer to run (or without having to run `arch-update --check` manually via the terminal)
=> feat: Add a right click menu entry to trigger a check for updates in the systray applet

po/arch-update.pot, po/fr.po, src/lib/check.sh, src/lib/full_upgrade.sh, src/lib/tray.py
Show the number and the list of pending updates in the systray applet tooltip, shown when hovering the mouse over the systray icon.
Closes https://github.com/Antiz96/arch-update/issues/154
=> feat: Show the number and the list of pending updates in systray's tooltip

res/desktop/arch-update-tray.desktop, res/desktop/arch-update.desktop
Fix icons name in the `arch-update.desktop` and `arch-update-tray.desktop` files to get the icons back in application menus.
Before:
After:
Fixes https://github.com/Antiz96/arch-update/issues/261
=> fix: Fix icons name in desktop files

res/desktop/arch-update-tray.desktop, res/desktop/arch-update.desktop
Add a comment entry to the `arch-update.service` & `arch-update-tray.service` to serves as a short description in applications menus.
Before:
After:
=> feat: Add a description to desktop files

po/arch-update.pot, po/fr.po, src/lib/check.sh, src/lib/list_packages.sh, src/lib/tray.py
Update the "updates" state file on package listing in `arch-update` / `arch-update --list` to avoid having an different & outdated updates list in the systray applet tooltip (compared to the actual refreshed list given by the package listing)
See the outdated / incomplete list from the tooltip compared to the package listing:
=> fix: Update the "updates" state file on package listing

README-fr.md, README.md, doc/man/arch-update.1, doc/man/fr/arch-update.1
Document the potential the workaround for the eventual race condition that can potentially happen when starting the systray applet automatically at boot (resulting in the systray applet failing to start).
Closes https://github.com/Antiz96/arch-update/issues/269
=> doc: Document the workaround for the race condition potentially happening when starting the systray applet at boot

.github/workflows/CI.yml, po/arch-update.pot, po/fr.po, src/lib/tray.py
Add a dynamic menu entry containing the state of the system and an associated dropdown menu containing the list of available updates. This serves as an alternative to the dynamic tooltip (which may not supported on every panel / systray implementation)
Closes https://github.com/Antiz96/arch-update/issues/260
=> feat: Add a dynamic dropdown menu containing the list of available updates to the systray applet menu

src/lib/orphan_packages.sh
Fixes the parsing for unused runtimes to avoid false positives, as discussed in the issue.
Fixes https://github.com/Antiz96/arch-update/issues/285
=> Fix False Positive for Unused Runtimes when Flatpak has Runtimes Pinned

README-fr.md, README.md, doc/man/arch-update.conf.5, doc/man/fr/arch-update.conf.5, res/config/arch-update.conf.example, src/lib/config.sh
Removed the AlwaysShowNews option
Closes #284
=> chore: Removed the AlwaysShowNews option

src/lib/list_news.sh
The command historically used for news path parsing was chaining multiple 'sed' calls in an unoptimized way. Everything is now merged into a single 'sed' call.
=> chore: Optimize news path parsing when listing Arch news

src/arch-update.sh, test/case/basic_functions.bats
Rename the `TEST_LIBDIR` environment variable to `ARCH_UPDATE_LIBDIR`, which is more specific name wise (to avoid eventual conflicts) and is more generic usage wise (as it could be useful outside of `make test`, e.g. for people that want to use a custom library directory).
=> chore: Rename LIBDIR env var

src/lib/list_news.sh
Corrected parsing of the article info section to support the new format.
[Author tag incorrectly parsed in news](https://github.com/Antiz96/arch-update/issues/291)
=> fix: Author tag incorrectly parsed in news

README-fr.md, README.md, doc/man/arch-update.conf.5, doc/man/fr/arch-update.conf.5, src/lib/common.sh
Use /usr/bin/env to set the DIFFPROG environment variable for the execution of pacdiff. The manpages and READMEs were also changed to remove the note about DiffProg and doas
=> feat: apply DiffProg setting when using doas

README-fr.md, README.md, doc/man/arch-update.1.scd, doc/man/fr/arch-update.1.scd
The previous documentation to force the usage of an alternative terminal emulator was "messy" and mildly accurate.
This commit updates the documentation to recommended the usage of the [xdg-terminal-exec](https://github.com/Vladimir-csp/xdg-terminal-exec) specification instead, which is a way more sane approach.
Closes https://github.com/Antiz96/arch-update/issues/289
=> doc: Document the usage of `xdg-terminal-exec` to run Arch-Update in a specific terminal emulator

README-fr.md, README.md, doc/man/arch-update.1.scd, doc/man/arch-update.conf.5.scd, doc/man/fr/arch-update.1.scd, doc/man/fr/arch-update.conf.5.scd, res/icons/README.md
Remove in-depth, repetitive and superfluous details from the documentation to its improve overall readability and ease its maintenance.
=> doc: General rework & simplification of the documentation

src/lib/check.sh, src/lib/common.sh, src/lib/list_packages.sh, src/lib/orphan_packages.sh
Rename 'notif' and 'flatpak' variables to 'notification_support' and 'flatpak_support' respectively for a better clarity / to avoid confusions.
=> chore: Use more specific names for 'notif' and 'flatpak' variables

src/lib/check.sh, src/lib/list_packages.sh
`paru` still shows packages listed in pacman.conf's `IgnorePkg` array when checking for update with `-Qua`, creating false positives when checking for updates with `arch-update`. This commit properly filters out packages tagged as `[ignored]` from the `paru` output to prevent such false positives.
*For information, `pikaur` also shows packages listed in `IgnorePkg` in its output but in `stderr`, which is already filtered out by `arch-update` (so no fix needed for `pikaur`). `yay` completely ignores packages listed in `IgnorePkg` already (just like `checkupdates` does for packages from the repos).*
From https://github.com/Antiz96/arch-update/issues/304:
```text
$ arch-update
==> Looking for updates...
==> AUR Packages:
bcompare 4.4.7.28397-1 -> 5.0.5.30614-1 [ignored]
-> Proceed with …
```
=> fix: Filter out ignored packages when checking for AUR packages update with paru

doc/man/arch-update.conf.5.scd, doc/man/fr/arch-update.conf.5.scd, res/config/arch-update.conf.example, src/lib/common.sh, src/lib/config.sh
Add the `NoFlatpak` option in the `arch-update.conf` configuration file to ignore Flatpak packages support (even if `flatpak` is installed).
=> feat: Add the `NoFlatpak` option to `arch-update.conf`

doc/man/arch-update.conf.5.scd, doc/man/fr/arch-update.conf.5.scd, res/config/arch-update.conf.example, src/lib/common.sh, src/lib/config.sh
Add the `NoAUR` option in the `arch-update.conf` configuration file to ignore AUR packages support (even if `paru`, `yay` or `pikaur` is installed).
=> feat: Add the `NoAUR` option to `arch-update.conf`

res/config/arch-update.conf.example
The link to the README currently contained in the default / example configuration file for its documentation is outdated.
=> doc: Update man page link in default / example configuration file

Makefile
`gzip` saves timestamps by default, which prevents reproducible builds.  
Get rid of timestamps with the `-n` option to make Arch-Update reproducible.
=> chore: Get rid of gzip timestamps during build to make Arch-Update reproducible

Makefile
Compressing man pages is a distribution / user preference that should be handled on the packaging side of things.
Indeed, compressing man pages by default imposes a compression algorithm / level for users whereas most package managers handle that already and allow users to choose / configure them (if wanted at all). Additionally, it can lead to unexpected side effects. For instance, gzip recording timestamps in metadata by default, which prevents reproducible builds (see https://github.com/Antiz96/arch-update/commit/905f6413ba629db527a931a866e9f6f55bb211c3).
See https://cmpct.info/~sam/blog/posts/automatic-manpage-compression/ for detailed rational.
=> chore(man): Don't compress man pages during build

doc/man/arch-update.1.scd, doc/man/fr/arch-update.1.scd, src/lib/common.sh, src/lib/gen-config.sh, src/lib/tray.sh
Make scripts exit on `mkdir` failures to avoid running tasks with an non-existent `tmpdir`, `statedir` or `configdir` for instance.
=> chore: Make scripts more robust when using `mkdir`

README-fr.md, README.md, src/lib/tray.py
Having the list of pending updates in the tooltip is kinda a bad design and creates more issues than it solves.  
See https://github.com/Antiz96/arch-update/issues/319 for full rational.
Closes https://github.com/Antiz96/arch-update/issues/319
=> chore: Remove the list of pending updates from the systray's tooltip

src/lib/tray.py
- More precise variables names
- More precise comments
- Add the missing swedish translation
No major changes, this is just to ease maintenance on my side.
=> chore: Little rework of the systray applet python script

README-fr.md, README.md, doc/man/arch-update.1.scd, doc/man/fr/arch-update.1.scd
Enhance the documentation about race condition to mention the eventual issue where click actions misbehave (e.g. right click also runs `Arch-Update` in addition of opening the menu).
Closes https://github.com/Antiz96/arch-update/issues/324
=> doc: Enhance documentation about race condition

src/lib/full_upgrade.sh
Do not source / load the `kernel_reboot` library when running from WSL. Running this library from WSL makes no sense (as the kernel is managed by WSL itself) and create false positives.
=> fix(kernel_reboot): Don't source the kernel_reboot lib in WSL

Makefile
Description:
Fixes incorrect paths in the uninstall target of the Makefile for arch-update. Additionally, the Swedish translation file was missing from the removal list.
Changes:
Corrected the path for .mo files.
Added Swedish (sv) translation file to the uninstall target.
Before:
rm -f "${DESTDIR}${PREFIX}/usr/share/locale/fr/LC_MESSAGES/${_pkgname}.mo" rm -f "${DESTDIR}${PREFIX}/usr/share/locale/zh_CN/LC_MESSAGES/${_pkgname}.mo"
After:
rm -f "${DESTDIR}${PREFIX}/share/locale/fr/LC_MESSAGES/${_pkgname}.mo" rm -f "${DESTDIR}${PREFIX}/share/locale/sv/LC_MESSAGES/${_pkgname}.mo" rm -f "${DESTDIR}${PREFIX}/share/locale/zh_CN/LC_MESSAGES/${_pkgname}.mo"
Testing:
Ran make uninstall and confirmed that all translation files are properly removed.
=> Fix: incorrect paths in uninstall target of Makefile

CHANGELOG.md, src/lib/tray.py
Some panels open dropdown menus in an arbitrary direction depending on different parameters such as the position of the applet in the tray area, the content length, the screen size, etc.. With dropdown sub-menus, this can result in overlaps on the main menu, preventing the main menu from being seen / used (see screenshot below).
To prevent that, the dropdown sub-menus for each update sources are dropped in favor of "top level" dropdown menus (which cannot overlap with the main menu), right under the "update count" menu entry (see screenshot below).
They work the same way as the previous sub-menus:
- Dropdown menus for sources with 0 pending update are not shown.
- The "All" dropdown menu is only shown when relevant (meaning when at least two sources have pending updates).
- The …
=> fix(systray): Drop sub-menus for update sources in favor of "top level" dropdown menus

src/lib/tray.py
Add a trigger to run Arch-Update when the "X update(s) available menu entry" is clicked (in addition of the dedicated "Run Arch-Update" menu entry).
This allows users to act on pending updates by being able to run Arch-Update from the first menu entry, without having to move down to the dedicated "Run Arch-Update" one (which, since [this PR](https://github.com/Antiz96/arch-update/pull/355), will be moved lower than it currently is when there's pending updates available).
=> feat(systray): Run arch-update when clicking on the "X update(s) available" menu entry

po/arch-update.pot, po/de.po, po/fr.po, po/hu.po, po/sv.po, po/zh_CN.po, src/lib/tray.py, src/lib/tray.sh
Fix the systray applet crash occuring when the 'updates' state file does not exists on the system by correcting the `QAction` attribute for the main menu entry ("classic" menu entries use `setText` rather than `setTitle`).
Also, create the 'updates' state file if it doesn't exists when starting the systray applet (to prevent unnecessary error logs).
Finally, update the initial menu entry text to "Arch-Update" ("Checking for updates..." is actually wrong and misleading).
```text
$ arch-update --tray
State updates file does not exist: /home/antiz/.local/state/arch-update/last_updates_check
State updates file missing
Traceback (most recent call last):
File "/usr/share/arch-update/lib/tray.py", line 142, in update_dropdown_menus
with open(self.updatesfile, encoding="utf-8") as f: …
```
=> fix(systray): Fix crash when the 'updates' state file does not exist

README-fr.md, README.md, doc/man/arch-update.conf.5.scd, doc/man/fr/arch-update.conf.5.scd, res/config/arch-update.conf.example, res/desktop/arch-update-tray.desktop, res/desktop/arch-update.desktop, res/icons/README.md, src/lib/config.sh
The "light" and "dark" systray icon are barely visible when using a theme of the same tone. The "blue" one has the advantage of being visible on most theme variants and therefore might be a better default.
Users can still switch to their prefered icon variant via the `TrayIconStyle` option in the `arch-update.conf` configuration file.
=> feat: Make the blue systray icon the default

doc/man/arch-update.1.scd, doc/man/fr/arch-update.1.scd, po/arch-update.pot, po/de.po, po/fr.po, po/hu.po, po/sv.po, po/zh_CN.po, src/lib/full_upgrade.sh
Add a lock file to the main "full_upgrade" function to avoid multiple parallel run of Arch-Update.
Closes https://github.com/Antiz96/arch-update/issues/376
=> feat: Add a lock file to avoid multiple parallel runs

README.md
- When building from source, `sudo` is unnecessary except for installation and uninstallation.
=> doc(README): remove unnecessary sudo

src/lib/check.sh, src/lib/common.sh, src/lib/full_upgrade.sh, src/lib/kernel_reboot.sh, src/lib/list_packages.sh
The temporary pacman database created by `checkupdates` can only be accessed by one single `checkupdates` run at the time, resulting in the following error when two (or more) updates checks are being run at the same time within Arch-Update (e.g. if you run Arch-Update or trigger a check for updates at the same time as the automatic one executed by the systemd timer):
```
==> ERROR: Cannot fetch updates
```
To prevent that, we are now creating a temporary database directory for each checks, preventing the above issue to occur in the case when multiple check for updates are running at the same time (since they will now all have their own dedicated temporary database directory).
Database directories are deleted once checks are done, as there's no purpose keeping them around.
This involves to …
=> fix: Avoid collisions during parallel updates checks

src/lib/tray.sh
Instead of failing if a process for the systray applet is already running, we are now failing if a process for the systray applet is already running for the current user.
This allows multiple users to run the systray applet at the same time without collision.
=> fix(systray): Allow systray applet to run for multiple users

src/lib/full_upgrade.sh
Expand the condition to skip running the kernel upgrade detection to containers (rather than just WSL specifically).
Addresses https://github.com/Antiz96/arch-update/issues/389
=> fix(kernel upgrade detection): Expand skip condition to containers

src/lib/common.sh
Fix parsing for the DiffProg command to avoid unexpected error when verifying if said command is available on the system (in case in contains spaces for specific options, e.g. `nvim -d`).
=> fix(DiffProg): Fix command parsing

src/arch-update.sh, src/lib/common.sh
Make requirement checks less aggressive but only running them when relevant (rather than running them every time).
This is to avoid unexpected errors for certain options / arguments (e.g. a wrong AUR helper in the `arch-update.conf` configuration file that would prevent to run the `--news` option, even though said option doesn't depend on an AUR helper at all).
=> fix: Relax requirement checks

src/lib/full_upgrade.sh
If `kernel-modules-hook` is installed, the reboot detection is not useful and will at the moment always show that there's no pending kernel update, even if there is. This skips the detection if that package is installed to prevent user confusion.
Fixes: #396
=> Skip reboot check if kernel-modules-hook is installed

src/lib/check.sh
Fix updates count in desktop notifications.
The disown logic was happening too soon for the count logic to be handled properly.
Missing count in desktop notification:
Error when running `arch-update --check`
```
$ arch-update --check
wc: /home/antiz/.local/state/arch-update/current_updates_check: No such file or directory
/usr/share/arch-update/lib/check.sh: line 54: [: : integer expected
```
=> fix(notification): Fix updates count

src/lib/list_news.sh
The current logic for parsing news URL assumed that the URL path would always match the title of the news entry, which turned out to not necessarily be the case, resulting in eventual wrongly parsed URL paths.
This commit makes the logic to parse URL paths more robust by relying on the actual path as defined as `href` in the https://archlinux.org/news source code (and, as a bonus, it also allows to *finally* get rid of that `sed` monstrosity).
```text
$ arch-update --news
==> Looking for recent Arch News...
==> Arch News:
1 - zabbix >= 7.4.1-2 may require manual intervention
2 - linux-firmware >= 20250613.12fe085f-5 upgrade requires manual intervention
3 - Plasma 6.4.0 will need manual intervention if you are on X11
4 - Transition to the new WoW64 wine and wine-staging
5 - Valkey to …
```
=> fix(news): Make URL path parsing more robust

src/lib/list_news.sh
We now initiate a connection before checking the news to avoid being hit by the initial connection reset implied by the protection implementation to mitigate the [service outages](https://archlinux.org/news/recent-services-outages/) that Arch Linux is currently suffering from.
This commit adds default timeout to said request.
=> fix(news): Add default timeout to the initial connection request

po/arch-update.pot, po/de.po, po/fr.po, po/hu.po, po/sv.po, po/zh_CN.po, src/lib/common.sh, src/lib/full_upgrade.sh, src/lib/notification.sh, src/lib/tray.sh
The "Run Arch-Update" click action in the desktop notifications was broken due to the related "lockfile" variable not being passed correctly to the `systemd-run` environment the notification library is executed in.
After a second thought, there's no need for those "lockfiles" to be put in variables in the first place. They can just be called explicitly where needed.
=> fix(notification): Fix "Run Arch-Update" click action
